"""Canonical-query search relevance fixture (#172).

The most-used surface in a component library's docs is search: the very first
query a visitor types is a product noun like "button" or "modal". This module
asserts that those canonical queries rank a docs/component page first — and,
critically, that a *release note* never tops a product noun (the original
defect: searching "button" returned the "chirp-ui 0.2.2" changelog as #1).

It is a fixture, not a unit of theme code: it loads the **committed prebuilt
Lunr index** (``site/public/search-index.json``) plus the page data
(``site/public/index.json``) and replays queries the way ``core/search.js``
does at runtime. The index is generated by ``poe docs-build``; when it has not
been built the whole module skips gracefully so a fresh checkout's ``pytest``
run stays green.

Ranking levers this fixture guards (see ``site/config/_default/search.yaml``):
  - ``search_keywords`` frontmatter (8x boost) routes nouns without a dedicated
    page to the closest component doc (e.g. "button" -> Control selection).
  - Long-form ``content`` keeps changelog entries from out-ranking docs.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SITE_PUBLIC = REPO_ROOT / "site" / "public"
PREBUILT_INDEX = SITE_PUBLIC / "search-index.json"
PAGE_INDEX = SITE_PUBLIC / "index.json"
COMPONENT_DOCS_DIR = REPO_ROOT / "site" / "content" / "docs" / "components"

# Sections that are changelogs/release notes, never the right top hit for a
# product noun. The whole point of #172.
RELEASE_SECTIONS = {"releases", "changelog"}

# Sections that count as legitimate documentation destinations. A tutorial that
# teaches you to render a button is a fine #1 for "button"; a changelog is not.
# "notebook" is a first-class learning family (a "render a card from Python"
# notebook is a fine #1 for "card") — see #146/#147.
DOC_SECTIONS = {
    "components",
    "docs",
    "theming",
    "tutorial",
    "notebook",
    "guide",
    "patterns",
    "tracks",
}

lunr = pytest.importorskip("lunr", reason="lunr package not installed")
from lunr.index import Index  # noqa: E402  (after importorskip)


def _load_index():
    """Load the prebuilt Lunr index and page lookup, or skip if not built."""
    if not PREBUILT_INDEX.exists() or not PAGE_INDEX.exists():
        pytest.skip(
            "search index not built — run `uv run poe docs-build` to generate "
            "site/public/search-index.json + index.json"
        )

    idx = Index.load(json.loads(PREBUILT_INDEX.read_text(encoding="utf-8")))
    data = json.loads(PAGE_INDEX.read_text(encoding="utf-8"))
    pages = data.get("pages", [])
    if not pages:
        pytest.skip("index.json has no pages")

    by_ref = {(p.get("objectID") or p.get("href")): p for p in pages}
    return idx, by_ref


def _ranked(idx, by_ref, query: str) -> list[dict]:
    """Return ranked page dicts for *query*, best first."""
    results = []
    for hit in idx.search(query):
        page = by_ref.get(hit["ref"])
        if page is not None:
            results.append(page)
    return results


def _describe(page: dict) -> str:
    return f"{page.get('title')!r} [{page.get('section')}] {page.get('href')}"


# Canonical queries every component-library visitor types early. Each maps to
# the page (by href) we expect to win, or None when "any non-release doc page"
# is the bar (e.g. a noun whose best home is a tutorial or the catalog).
CANONICAL_QUERIES = {
    "modal": "/docs/components/modals/",
    "tabs": "/docs/components/tabs/",
    "dropdown": "/docs/components/dropdowns/",
    "drawer": "/docs/components/drawers-trays/",
    "tray": "/docs/components/drawers-trays/",
    "ascii": "/docs/components/ascii/",
    "theming": None,
    "button": None,
    "card": None,
}


@pytest.mark.parametrize("query", sorted(CANONICAL_QUERIES))
def test_canonical_query_does_not_rank_release_note_first(query: str) -> None:
    """A product noun must never surface a changelog/release note as #1."""
    idx, by_ref = _load_index()
    ranked = _ranked(idx, by_ref, query)
    assert ranked, f"no results for canonical query {query!r}"

    top = ranked[0]
    assert top.get("section") not in RELEASE_SECTIONS, (
        f"search {query!r} ranked a release note first: {_describe(top)}"
    )


@pytest.mark.parametrize(
    ("query", "expected_href"),
    [(q, href) for q, href in sorted(CANONICAL_QUERIES.items()) if href],
)
def test_component_query_resolves_to_component_page(query: str, expected_href: str) -> None:
    """Single-component nouns resolve to that component's docs page at #1."""
    idx, by_ref = _load_index()
    ranked = _ranked(idx, by_ref, query)
    assert ranked, f"no results for {query!r}"

    top = ranked[0]
    assert top.get("href") == expected_href, (
        f"search {query!r} expected {expected_href} first, got {_describe(top)}"
    )


@pytest.mark.parametrize("query", ["button", "card", "theming"])
def test_open_query_lands_on_documentation(query: str) -> None:
    """Nouns without a dedicated page still land on docs, not a changelog.

    "button"/"card" have no per-component page, so the bar is: the top result is
    a documentation page (component catalog, tutorial, or guide) — not API noise
    and not a release note.
    """
    idx, by_ref = _load_index()
    ranked = _ranked(idx, by_ref, query)
    assert ranked, f"no results for {query!r}"

    top = ranked[0]
    assert top.get("section") in DOC_SECTIONS, (
        f"search {query!r} should land on a documentation page, got {_describe(top)}"
    )


def test_search_keywords_populated_in_component_frontmatter() -> None:
    """#172 acceptance: search_keywords is populated (not an inert 8x boost).

    Reads the component docs' frontmatter directly so the assertion holds even
    before the site is rebuilt. The 8x search_keywords boost was noise while 0
    pages carried the field; at least one component doc must now populate it.
    """
    pytest.importorskip("yaml", reason="PyYAML not installed")
    import yaml

    populated = 0
    checked = 0
    for md in sorted(COMPONENT_DOCS_DIR.glob("*.md")):
        if md.name == "_index.md":
            continue
        text = md.read_text(encoding="utf-8")
        if not text.startswith("---"):
            continue
        _, _, rest = text.partition("---\n")
        front_raw, sep, _ = rest.partition("\n---")
        if not sep:
            continue
        front = yaml.safe_load(front_raw) or {}
        checked += 1
        kw = front.get("search_keywords")
        if isinstance(kw, list) and kw:
            populated += 1

    assert checked, "no component docs found to inspect"
    assert populated, (
        "no component doc populates search_keywords — either populate the "
        "frontmatter field or drop the 8x boost from the ranking contract (#172)"
    )
